### ISSUE TITLE
Lighting Panels can't be rotated or dyed

### ISSUE THREAD

**Issue by IO2I** [TeamGalacticraft/Galacticraft-Legacy#47] opened 2022-02-07 21:57 UTC
### Forge Version

14.23.5.2859

### Galacticraft Version

4.0.2.283

### Reproduction steps

1. Place Lighting Panel
2. Attempt to Rotate
3. Attempt to Dye

**Comment by ROMVoid95** [comment] 2022-02-07 23:14
What are you using to rotate/and dye it with?

**Comment by IO2I** [comment] 2022-02-08 01:24
> What are you using to rotate/and dye it with?

Ok, I solved the issue. I thought you could just right click dyes onto the lighting panel.

**Comment by ROMVoid95** [comment] 2022-02-08 02:37
okay, I'll assume this can be closed as its working as intended. If this is not the case, go ahead and re-open.

**Closed by ROMVoid95** 2022-02-08 02:37 UTC
Labels: Cannot Reproduce
