### ISSUE TITLE
Screen stuck at "Taking one big leap"

### ISSUE THREAD

**Issue by alankasprzyk23** [TeamGalacticraft/Galacticraft-Legacy#70] opened 2022-06-19 20:00 UTC
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.280

### Log or Crash Report

https://gist.github.com/alankasprzyk23/af657067b2e839f1987a515a4b9c03ac

### Reproduction steps

1. Started the rocket
2. Went up into the air
3. Clicked "Launch" on moon (crashes on any planet)
4. Stuck on "Taking one big leap"
5. Server crashes

Its some third-party mod causing this because I deleted other mods ecxept GalacticraftCore, Galacticraft: Planets and MicDoodleCore, it worked.

Do I really have to go through mod by mod to resolve this or can someone tell me what mod it is?

Mods:
![image](https://user-images.githubusercontent.com/77508096/174498296-6c4e59ff-598b-4f2f-a2ed-b1616ab0adef.png)

**Comment by embeddedt** [comment] 2022-06-20 01:51
Hi there, your crash was caused by Better Portals by the looks of it. Hope that helps!

**Comment by ROMVoid95** [comment] 2022-06-20 04:34
@embeddedt is correct, Better Portals is incompatible. Closing since reported crash is caused by another mod and not Galacticraft

**Closed by ROMVoid95** 2022-06-20 04:34 UTC
Labels: Mod Incompatibility, [Type] Bug Report

**Comment by alankasprzyk23** [comment] 2022-06-20 19:11
Tysm guys!
